### ISSUE TITLE
Add Proper Comments and Descriptions for UserService, SensorService, and ActuatorService

### ISSUE THREAD

**Issue by RomeoIndiaJulietUniform** [RomeoIndiaJulietUniform/AquaManage_Backend#2]
#### Description
To enhance code maintainability and readability, we need to add comprehensive comments and descriptions to the following implemented services and their corresponding test classes:
- **UserService**
- **SensorService**
- **ActuatorService**

Each service and its test class should have detailed comments explaining the purpose of classes, methods, and parameters. This will help future developers (and ourselves) understand the code more easily.

#### Tasks
1. **UserService**
   - Add comments to describe the purpose of the service and its main functionalities (e.g., user authentication, registration).
   - Document each method, including parameters and return types.
   - In the corresponding test class, add comments to explain the purpose of each test case and the expected outcomes.

2. **SensorService**
   - Describe the role of the service in managing sensor data.
   - Comment on each method that handles sensor readings and data processing.
   - In the corresponding test class, document each test case to clarify what aspect of the service is being tested.

3. **ActuatorService**
   - Explain the actuator service's purpose and how it interacts with other components.
   - Document methods that control or monitor actuators.
   - In the corresponding test class, provide descriptions for each test case, outlining the functionality being validated.

#### Best Practices
- Use Javadoc or similar documentation standards to ensure comments are clear and structured.
- Keep comments concise but informative; avoid redundancy with the code itself.
- Use meaningful variable and method names to enhance self-documentation.
- Follow a consistent commenting style across all services and test classes for uniformity.
- Review existing comments for accuracy and relevance, updating as necessary.

#### Acceptance Criteria
- All specified services and their test classes should have comments and documentation added according to the outlined tasks.
- The comments should adhere to best practices for code documentation.
- Ensure that all changes are committed to the repository with clear commit messages.

**Comment by MadhurSaluja** [comment]
Hey @RomeoIndiaJulietUniform If fine by you I would like to work on this

**Comment by RomeoIndiaJulietUniform** [comment]
Hii @MadhurSaluja, thanks a lot for showing interest in the project. I'm happy to inform you that I have assigned this issue to you.   Happy Coding 🙂

**Comment by varshalohakre** [comment]
hey! is this issue solved?? if not can you please assign me the task please?

**Comment by RomeoIndiaJulietUniform** [comment]
Hii @varshalohakre , thanks a lot for showing interest in this project. I am going to assign this task along with @MadhurSaluja . Your pull requests will be the key differentiators.

Please work on your solutions independently and submit a pull request when you're ready. I will review and merge the one that best meets our requirements.

Looking forward to seeing your contributions!

Thanks a lot again 🙂

**Comment by varshalohakre** [comment]
thank you!
i will try my best!

**Comment by Hemachandra6** [comment]
Hi @RomeoIndiaJulietUniform, I would like to work on this. Let me know if i can.

**Comment by RomeoIndiaJulietUniform** [comment]
Hii @Hemachandra6  thanks a lot for showing interest in this project. I am going to assign this task along with @MadhurSaluja and @varshalohakre . The pull requests will be the key differentiators.  Happy Coding !!!

**Comment by Hemachandra6** [comment]
Hey @RomeoIndiaJulietUniform, The comments and description are needed to be added to all the service and test classes. right? Not controller class methods and other?

**Comment by RomeoIndiaJulietUniform** [comment]
Nope, you need to define the controllers, JWT all. The PR should define and explain each method for the contributor's understanding and maintainability.

**Comment by varshalohakre** [comment]
task is done please tell me if any changes are needed!

**Comment by Hemachandra6** [comment]
Hey @RomeoIndiaJulietUniform, I have completed the task and raised PR. Please review and let me know if any more enhancement needed. Thanks in advance!

**Comment by RomeoIndiaJulietUniform** [comment]
Hii Everyone, the issue is now closed via the PR  #8 . I look forward to seeing more contributions from all of you in the project soon! 🚀
