### ISSUE TITLE
Add Proper Tests and Debugging methods for UserService, SensorService, ActuatorService

### ISSUE THREAD

**Issue by RomeoIndiaJulietUniform** [RomeoIndiaJulietUniform/AquaManage_Backend#3]
#### Description
We need to integrate SLF4J (Simple Logging Facade for Java) logging functionality into the existing services to ensure proper logging of events, errors, and informational messages. Additionally, the `README.md` file needs to be updated to reflect the purpose of the services and how the logging system is used.

#### Tasks
1. **Integrate SLF4J Logger**
   - Add SLF4J dependencies to the project (if not already present).
   - Implement SLF4J logging in the following services:
     - **UserService**
     - **SensorService**
     - **ActuatorService**
   - Replace `System.out.println` calls (if any) with proper log levels (e.g., `info`, `debug`, `error`).
   - Ensure that critical operations, errors, and key events are logged at appropriate levels in each service.

2. **Update `README.md`**
   - Add a section in `README.md` that describes how logging is implemented using SLF4J.
   - Provide instructions on how to configure logging levels (if necessary).
   - Mention any external configuration files (like `logback.xml` or `log4j2.xml`) if used for logging.
   - Explain the purpose and functionality of the following services in the `README.md`:
     - **UserService**
     - **SensorService**
     - **ActuatorService**

#### Best Practices for Logging
- Use `info` for standard operation messages.
- Use `debug` for detailed, low-level technical details that are useful for debugging.
- Use `error` for logging exceptions and failures.
- Ensure that sensitive data (such as passwords) is not logged.

#### Acceptance Criteria
- SLF4J logging should be fully integrated into the **UserService**, **SensorService**, and **ActuatorService**.
- The `README.md` file should clearly explain the services and how the logging system works.
- The changes should follow logging best practices and should be properly committed to the repository with clear commit messages.

**Comment by himanshuyadav62** [comment]
I want to work on this enhancement , can you assign this to me

**Comment by melisolmez** [comment]
Hi, I want to work on this issue. Could you assign to me?

**Comment by RomeoIndiaJulietUniform** [comment]
Hii @melisolmez ,thanks a lot for showing interest in the project. I'm happy to inform you that I have assigned this issue to you. Happy Coding 🙂!
